// Auto-generated by Payload. Do not edit by hand — running
// `payload generate:importmap` (or `next dev`) rewrites this file.
export const importMap = {}
import { VercelBlobClientUploadHandler } from '@payloadcms/storage-vercel-blob/client'

export const importMap = {
  '@payloadcms/storage-vercel-blob/client#VercelBlobClientUploadHandler': VercelBlobClientUploadHandler,
}
